source "https://rubygems.org"

gem "smart_prompt", "~> 0.4.2"
gem "better_prompt", "~> 0.2.1"
gem "mcp-sdk.rb", "~> 0.1.2"
gem "ruby_rich", "~> 0.4.0"
gem "sequel"
gem "pg"
gem "unicode-display_width", "~> 3.1"
gem "rdbg", "~> 0.1.0"
