adapters:
  openai: OpenAIAdapter
logger_file: ./log/prompt.log
database:
  docs: postgres://docs:ment@localhost/docs
llms:
  SiliconFlow:
    adapter: openai
    url: https://api.siliconflow.cn/v1/
    api_key: ENV["APIKey"]
    default_model: Qwen/Qwen2.5-7B-Instruct
  llamacpp:
    adapter: openai
    url: http://localhost:8080/    
  ollama:
    adapter: openai
    url: http://localhost:11434/
    default_model: deepseek-r1
  deepseek:
    adapter: openai
    url: https://api.deepseek.com
    api_key: ENV["DSKEY"]
    default_model: deepseek-reasoner
  gitee:
    adapter: openai
    url: https://ai.gitee.com/v1
    api_key: ENV["GITEEKEY"]
  aliyun:
    adapter: openai
    url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: ENV["ALIKEY"]
default_llm: SiliconFlow
worker_path: "./workers"
template_path: "./templates"